ign-packo/PackO

- itowns/Saisie.js
Problème de précision dans la saisie des polygones de patch.
> Fix probleme de simple précision sur les three js line geometry

- doc/swagger.yml
- itowns/index.html
- package-lock.json
- package.json
- routes/misc.js
- serveur.js
- test/misc.js
- récupération de la version git de l'API
- ajout d'une route pour la récupérer
- affichage dans itowns
> Affichage de la version git de l'API

- routes/patch.js
- optimisation: on vérifie pour chaque tuile s'il y a un pixel modifié plutôt que de se baser uniquement sur la BBox du patch
- correction: dans certain cas, il y a un pixel parasite en (0, 0), en particulier sur le patch n'est pas sur la tuile. On ajoute donc une ligne au masque pour être plus robuste
> optimisation + correction sur les patchs

- .github/lint-python.yml
> pylint/flake8 sur createCache.py

- .github/workflows/lint-python.yml
- scripts/createCache.py
Nettoyage des commits de create cache multi
> Create cache multi 2

- .github/workflows/lint-python.yml
- scripts/create_cache.py
Nettoyage des erreurs simples, il reste:
```
************* Module create_cache
scripts/create_cache.py:60:0: R0913: Too many arguments (8/5) (too-many-arguments)
scripts/create_cache.py:139:0: R0912: Too many branches (14/12) (too-many-branches)
scripts/create_cache.py:250:0: R0914: Too many local variables (29/15) (too-many-locals)
scripts/create_cache.py:339:0: R0914: Too many local variables (30/15) (too-many-locals)
scripts/create_cache.py:339:0: R0912: Too many branches (22/12) (too-many-branches)
scripts/create_cache.py:339:0: R0915: Too many statements (92/50) (too-many-statements)
------------------------------------------------------------------
Your code has been rated at 9.77/10 (previous run: 9.77/10, +0.00)
```
> clean pylint/flake8

- itowns/Saisie.js
- itowns/index.html
Gestion des couches opi, ortho et graph
- creation d'un objet unique contenant les 3 couches et les données associées
- Refactoring de l'actualisation des couches
> Refactoring itowns

- routes/patch.js
Améliorations:
- on analyse en amont les outOfBounds ce qui évite de commencer à patcher pour rien et de devoir effacer, etc...
- meilleur gestion asynchrone de l'application des patchs (cela va simplifier la PR pour la gestion multithread/workers)
> refactoring de l'application des patchs

- routes/patch.js
cela permet de corriger les failles des undo/redo (#59), on peut même s'interroger sur l'utilisation des liens symboliques (n'en sont plus).
> ajout du fichier history par tuile

- itowns/Saisie.js
Modifications :
- [Saisie.js] Réecriture de la manière de gérer le du polygone de saisie
- [Saisie.js] Ajout d'un _evenListener_ sur le bouton Suppr permettant d'effacer le dernier sommet entré
~~[se base sur la PR UpdateItowns #79 ]~~
> [itowns] Touche 'Suppr' et suppression du dernier sommet

- itowns/index.html
- itowns/index.js
Nouvelle fonctionnalité 
- centrage de la carte sur des coordonnées renseignées à la main
> [itowns/index] Saisie de coord et centrage

- README.md
- itowns/index.js
- itowns/package.json
- package.json
- regress/patch.js
- routes/patch.js
- serveur.js
Reprise de la branche de Greg 'static' et modifiée
> Static n°2

- scripts/cache.py
- scripts/cache_def.py
Permet de mesurer le temps mis par les différents traitements
Actif lorsque l'argument -v est supérieur à 1
Autre modif:
- Deplacement du moment de la création du fichier overview
> [cache] add Timer si verbose > 1

- routes/worker.js
Objectif:
- Pouvoir faire des retouches sur un cache qui n'est pas constitué de tuiles 256 * 256
> [API] dynamique tileSize

- itowns/package.json
MaJ package.json pour le passage a itowns 2.32
> MaJ itowns 2.32

- regress/patch.js
- rok4.js
- routes/graph.js
- routes/patch.js
- routes/wmts.js
- routes/worker.js
- serveur.js
Cette PR propose : 
- une homogénéisation du code serveur.js (utilisation de path.join)
- une modification du retour de la fonction permettant de retourner le chemin des tuiles rok4
-  ~~une correction de bug lié au 'clear'~~
(Sous partie de la PR Visualisation et sauvegarde des retouches)
> [API] Cleanup

- itowns/Saisie.js
- itowns/index.js
(basée sur PR #118 MaJ Itowns 2.32)
Objectifs : 
- gérer la gestion de la forme du curseur entre les actions itowns et les actions serveurs
> [itowns] Gestion de la forme du curseur

- itowns/index.js
objectif:
- limiter les niveau de zoom a ceux effectivement calculés, pour le cache en question (+/-1)
> fix(monitor): limit zoom to dataset lvls, not default lvls

- itowns/package-lock.json
- itowns/package.json
MaJ nouvelle release itowns 2.33.
Nouvelles fonctionnalités ajoutées : 
- contours
- fix précision polygon json
> build(monitor): update itowns 2.33

- scripts/cache.py
- scripts/cache_def.py
1) cache: Correction du timer pour le découpage des OPI
2) cache: dans le cas ou l'on a plus de cpu que d'image a traiter, limiter le nombre de cpu au nombre d'image.
> Quelques améliorations et correctifs

- doc/win/notice_anaconda_win.md
Ajout de la doc d'install pour anaconda sous Windows
> docs: anaconda install for windows

- itowns/Saisie.js
- itowns/index.js
PR pour la visualisation des patchs en cours.
Modifications:
- ajout d'une couche a partir du json de GET patches
> [monitor] Visualisation des saisies

- itowns/Saisie.js
- itowns/index.js
Objectifs:
- rendre la couche patches invisible par default
- rendre la propriété visible d'une couche pérenne entre branche
> Invisible patches

- db/db.js
- middlewares/graph.js
- middlewares/wmts.js
- regress/3_graph.js
- routes/graph.js
- ajout dans db d'une requête pour obtenir une OPI depuis une couleur
- adaptation de la route/middleware/regress pour les routes graph
- fix sur le middleware wmts pour l'identification de l'OPI dans GetFeatureInfo
> Route db graph

- README.md
- cog_path.js
- gdal_processing.js
- scripts/vectorise_graph.py
Add script to vectorise graph from a cache using the branch mecanics
Change extension for the GDAL scripts based on the OS (.bat for windows, .py otherwise)
> Gdal process

- itowns/css/View.css
- itowns/index.html
- itowns/index.js
> feat(monitor): add a graph visibility widget

- gdal_processing.js
Depuis la montée de version du module gdal_async, on récupère dans la console des warnings lorsqu'on applique des patchs sur l'ortho.
La doc du module gdal_async explique qu'il faut éviter d'utiliser des getter/setter (par exemple ds.rasterSize.x) avec des requêtes asynchrones (par exemple band.pixels.readAsync).
> fix(API): gdal async warning

- README.md
- scripts/vectorise_graph.py
Ajout d'un tuilage lors du calcul de l'export
Mise à jour du script d'export vecteur (ajout des étapes de merge/dissolve/make_valid)
Mise à jour de la doc en conséquence
> Gdal process v2

- README.md
- scripts/vectorise_graph.py
S'assurer qu'il n'y a bien des patches sur la branche qu'on souhaite exporter si elle est différente de orig.
> refactor: send error if not patch for id_branch

- regress/1_file.js
- regress/2_cache.js
- regress/3_branch.js
- regress/3_graph.js
- regress/4_patch.js
- regress/4_vector.js
- regress/4_wmts.js
- scripts/cache_def.py
Ajout des tests nécessaire concernant les caches RGBIR & IR
Branche basée sur cache_RVBIR2
> api(ci): added tests for rgbir/ir in file and cache - wip in branch

- itowns/Editing.js
Objectif:
- rendre impossible les fonctions Undo et Redo a des échelles > 1/16
> Undo Redo et echelle > 1/16

- itowns/index.js
Gestion du namecache inexistant ou incorrect dans l'url
> fix: incorrect namecache

- README.md
- scripts/vectorise_graph.py
Modification des variables nécessaires pour l'export vecteur
Les dossiers contenant les outils Gdal et Gdal/Ogr sont maintenant nécessaires dans le PATH
Mise à jour de la doc en conséquence
> Vectorise environment

- README.md
- itowns/Editing.js
- itowns/index.js
Mise en place des raccourcis clavier demandés dans le ticket #159 et j'ai ajouté en plus des raccourcis liés aux remarques. 
La liste des raccourcis est présente dans README.md
> Raccourcis clavier

- README.md
- itowns/css/View.css
- itowns/index.html
- itowns/index.js
Évolution de la gestion du paramètre namecache incorrect ou inexistant dans l'url :  l'utilisateur peut choisir un dans une liste contenant les noms des caches disponibles dans la base
> List caches

- itowns/index.js
Oubli lors d'une modification précédente sur la modification de coordonnées
> fix(monitor): message moved from editing to viewer

- package-lock.json
- package.json
Upgrade gdal-async to correct vulnerability in API
> fix(API): gdal-async upgrade

- README.md
- itowns/Editing.js
- itowns/index.js
Mise en place du raccourci pour basculer l'ortho et l'opi entre RVB/IR/IRC
> Raccourci RVB/IR/IRC

- README.md
fix pour la mise en page du ReadMe au paragraphe "Gestion des couches d'alertes"
> ReadMe : Corr de mise en Page "Gestion des couches d'alertes"

- db/db.js
- itowns/Editing.js
Correction d'un bug lié à la présence d'apostrophe dans le commentaire (ajout d'une remarque ou DnD d'une couche avec comment.
Et aussi des caractères spéciaux (&, /, \, etc...) lors d'une saisie a travers le monitor
> Gestion des caractères spéciaux dans le champ 'comment'

- itowns/Branch.js
Ajouts de test de vérification du nouveau nom de branche entrée a la suite d'un clique sur 'Add new branch'
Issue #227 
Le nom doit :
- être non vide
- commencer par un chiffre ou une lettre
- ne contenir que des caractères alphanumériques ainsi que - et _.
> Vérification du nom lors de l'ajout d'une branche

- db/db.js
- doc/swagger.yml
- itowns/Editing.js
- itowns/index.js
- middlewares/graph.js
- middlewares/patch.js
- middlewares/wmts.js
- regress/3_graph.js
- regress/4_patch.js
- regress/data/vector.json
- routes/patch.js
- routes/vector.js
Dans le cadre de la refactorisation a venir,
Un renommage/nettoyage de deux variables et suppression des références au terme "Cliche".
> Modification nom variable : ' -' -> '-', cliche -> opiName et Cliche dans le nom de fct et variable

- doc/swagger.yml
- gdal_processing.js
- itowns/Editing.js
- middlewares/graph.js
- middlewares/wmts.js
- regress/3_graph.js
Se base sur PR #311 (merged)
=> rebased
Modification des codes d'erreurs de l'API en lien avec les retours de GET /graph
\+ Changement sur la fonction gdalProcessing.getPixel() -> gdalProcessing.getColor()
> fetcher GET graph : modification des codes de retour et gestion erreur

- itowns/Controller.js
- itowns/Editing.js
- itowns/Viewer.js
- itowns/index.js
Suppression du doublon viewer.alertLayerName qui est identique a editing.alertLayerName
-> Ajout d'un attribut isAlert sur les ColorLayer
> Supp du doublon alertLayerName

- itowns/Branch.js
- itowns/Editing.js
- itowns/Menu.js
- itowns/Viewer.js
- itowns/index.html
- itowns/index.js
PR en lien avec l'issue #320 
Ajout d'une nouvelle classe Menu (a la place du module itowns GUItools)
- l'Object menu associé est attaché a menuDiv (div html)
Quelques refactorisations associés : 
- modification sur l'Object wmtStyle
- fusion des 2 objets shortcuts
- retravaille sur la façon de gérer une suppression de couche
> Ajout d'une classe pour le menu

- doc/swagger.yml
- itowns/Viewer.js
- itowns/index.js
- middlewares/wmts.js
- regress/4_wmts.js
- routes/wmts.js
En lien avec le ticket [RedMine#2075](http://redmine.forge-idi.ign.fr/issues/2075) 
Correction du flux WMTS pour QGIS et de la gestion du STYLE dans itowns
Correction de la régression #329
> feat(monitor,API): change wmtsStyle for Graph layer

- .github/workflows/coveralls.yml
- README.md
- scripts/cache.py
- scripts/cache_def.py
- scripts/cut_opi.py
- scripts/generate_tile.py
Version gpao de la création de cache proposée par Greg
Contient également les modifications nécessaires pour prendre en compte les évolutions qui avaient eu lieu :
- gestion de l'infrarouge
- gestion des métadonnées
> Createcache gpao v2

- README.md
- scripts/export_mtd.py
Corrections mineures sur l'ajout des métadonnées à l'export vecteur (ajout color sous forme : (r, g, b) et changement nom d'attribut name -> cliche) (#342 )
Maj doc concernant le format des métadonnées dans le graphe en entrée (ticket interne #2107)
> Mise à jour doc et export métadonnées

- gdal_processing.js
Correction du bug décrit dans #353.
> Fix API path IR

- itowns/Controller.js
- itowns/Editing.js
- itowns/index.js
Se base sur la PR #324 ClassAlert
Modifications : 
- gestion des raccourcis clavier issue #332 
- ajout d'une méthode Controller.setBackgroundColor()
- renommage et spécialisation de la méthode cancelPolygon() -> resetPolygon()
> Refactor Editing.js

- README.md
- cog_path.js
Correction des niveaux de COG (voir #350 )
> fix(API): COG levels

- README.md
- scripts/cache.py
> Fix table name

- gdal_processing.js
- scripts/cache_def.py
Correction du problème des contours épais si on n'est pas à pleine résolution décrit dans #362
> Fix resampling 'nearest' for graph cog

- itowns/Viewer.js
Correction du bug décrit dans #375
> Fix layer name

- itowns/package-lock.json
- package-lock.json
Correction de la vulnérabilité majeure liée à la version de Json5 dans l'API et client itowns
> fix(API,monitor): fix high severity vulnerability on json5

- README.md
- scripts/create_qgis_view.py
En accord avec la demande interne 2130 et la version de la doc à ce jour du même ticket, création de premiers éléments pour une vue PackO dans QGIS  :
- nouvelle branche PackO sur le cache en entrée
- ortho.xml et graph.xml - couches ortho et graphe de la nouvelle branche avec les modifications demandées
- contour_graph.vrt - couche contour graphe avec les ajouts et modifications demandés
Au moins dans un premier temps, j'ai gardé les fichiers "*_tmp" qui représentent les xml et vrt "bruts", exportés ou générés automatiquement, pour voir facilement les ajouts et modifications apportés dans les xml et vrt finaux
> Create qgis view: xml & vrt

- README.md
- scripts/create_qgis_view.py
- scripts/process_requests.py
- séparation des fonctions liées aux requêtes pour faciliter l'accès/utilisation
- changements dans la gestion de l'argument style_ortho
> Refactor create qgis view xml & vrt

- scripts/create_qgis_view.py
- scripts/process_requests.py
Remaniement sur la gestion de la réponse d'une requête
> refactor(qview): handle request response

- middlewares/pgClient.js
Gestion de connexions à la bd postgresql via 'pooling'  (https://node-postgres.com/apis/pool)
Cette branche est basée sur la branche `pooling_test` [(v1.7.0-2-g1c8064a)](1c8064a) testée en condition de prod
> feat(API): connection pooling to postgresql

- .github/workflows/lint-python.yml
- README.md
- ressources/example_macros_qgis.py
- scripts/create_qgis_view.py
- scripts/process_qlayers.py
- scripts/process_requests.py
Création de la vue PackO pour QGIS, comme décrit dans #392
> Create qgis view

- ressources/example_macros_qgis.py
- scripts/create_qgis_view.py
- scripts/process_qlayers.py
- correction sur la récupération des branches uniquement sur le cache de travail et non plus sur tous les caches de la base (car cela pouvait créer des problèmes de cohérence si on avait des branches avec même nom sur des caches différents)
- ajout de la possibilité de désactiver le formulaire pop-up des attributs, avec valeur par défaut 'désactivé'  pour les couches retouches_graphe et retouches_info
> Enhance Qgis view
