itowns/Saisie.js, itowns/index.html, serveur.js
1) Gestion du 'port' et du 'server' de manière dynamique : pour l'API, le swagger et itowns
2) Ajout d'une aide pour l'API (serveur.js --help)
Modification : Suppresion du '\\' final dans l'url de l'API dans itowns
=> Gestion port

itowns/Saisie.js, itowns/index.html
Modification du select et de l'interaction 'select' et 'polygon' : 
- cliquer sur 'select' n'efface pas le 'cliche' en cours
- cliquer sur 'polygon' alors que 'select' est actif, active la fonction de saisie uniquement dans le cas d'un cliche valide préalablement sélectionné
bonus : coords initiales définies sur le point centrale de la scene
=> Opi Select 2

itowns/index.html
Il y avait un bug lors du rechargement de la page itowns lorsqu'il arrive pas a contacter l'API, du au fait que localhost:8000 était écris en dur.
=> [itowns] Fix reload sur serveur not localhost

scripts/create_cache.py
Création du cache:
- ajout d'un argument pour paramétrer les niveaux de pyramide à calculer (--level)
Ce paramètre peut être un 'int' unique ou deux 'int' définissant le level min et le level max
Suppression du paramètre api devenu obsolète (depuis une version précédente)
=> Level as param

routes/graph.js, routes/patch.js, routes/wmts.js
Greg hier a fais part d'une confusion dans le level max qui amenait à une erreur dans le calcul de la résolution sur les 3 route de l'API utilisant ce calcul.
Cette branche vise à fixer cette erreur en enlevant les références à un lvlMax de l'overview ainsi qu'a un Rmax (la création de ces variables étant d'ailleurs inutile)
=> Fix confusion lvlMax dataset/overviews et erreur dans la valeur de résolution

package.json, routes/patch.js, serveur.js, test/file.js, test/graph.js, test/misc.js, test/patch.js, test/wmts.js
Nouvelle PR en remplacement de #53
accélérer le traitement des gros patchs. Actuellement, sur avec des OPI CamV2, l'application d'un patch couvrant 1/3 de la surface utile d'une OPI prend 4 min sur ma machine. 
On crée un pool de workers au niveau du serveur avec le nombre de threads par défaut (nb de coeurs de la machine -1). 
Il y a une variable globale (minJobForWorkers) qui permet de régler le nombre minimale de traitements avant d'enclencher l'utilisation des workers (pour éviter de pénaliser les petits patchs).
La parallélisation se fait à la fois au niveau de la préparation des patchs (lorsqu'on crée le masque et que l'on vérifie si on ne sort pas de la zone) et au niveau de l'application des patchs.
Il a été nécessaire de remplacer le module nyc par c8 dans les tests pour …
=> version multithread de l'application des patchs (v2)

scripts/cache_def.py
Lors de la phase de découpage :
Ne faire qu'une seule lecture du fichier OPI.tif et non plus réouvrir le fichier a chaque tuile.
=> [Creation du cache] Une seule lecture OPI.tif par decoupage

scripts/cache_def.py
J'ai modifié la requête SQL pour s'adapter aussi au cas où les noms des clichés dans le shp (et donc dans la BD) ne sont pas identiques aux noms des OPIs (et ainsi éviter d'avoir des requêtes sans réponse qui génèrent des tuiles ortho et graph noires, sans aucune information, dans le cache).
=> Adapt SQL request

itowns/index.js
(basée sur PR #118 MaJ Itowns 2.32)
Objectif:
- permettre le déplacement lors d'un clique molette long.
Question subsidiaire:
- Quel était le problème avec la mise à jour du curseur dans l'ancienne version itowns ?
J'ai l'impression qu'il n'y a plus de problème (et la suppression des lignes supplémentaire résout un bug d'affichage que j'ai rencontré lors d'une saisie de coordonnées.)  => Reglé dans la PR #110
=> [itowns] clique molette et deplacement

itowns/css/View.css, itowns/index.html, itowns/index.js
Objectifs : 
- Ajouter l'échelle et le niveau de zoom (de façon dynamique)
- Limiter les zooms aux niveaux présent dans le cache (exactement ou avec une marge ?)
Modifications :
- l'échelle ainsi que le niveau de zoom ont été ajoutés a la carte
- le zoom initial est un dézoom 4 (sujet à discussion)
- les zooms et dézooms sont actuellement limités aux niveaux renseignés dans le fichier overviews avec une marge de +/-1 (sujet à discussion)
- itowns (bug et amélioration) :
- ~~modifier la taille de la fenêtre change le niveau de zoom de façon incontrôlable~~ (corrigé dans itowns 2.32)
- ~~pas de moyen actuellement de limiter les zoom in et out~~ (ajouté dans itowns 2.32)
- ~~bug lors d'un long zoom et clique molette ou droit~~(corrigé dans itowns 2.33)
=> [itowns] Echelle et zoom

scripts/cache_def.py
Objectif:
- Lors d'un update,  des doublons dans le mtd_cache.json apparaissaient du au fait que la lecture du json transformait les clés initialement au format 'int'
> {1: {1: {1: 'image1', 2: 'image2'}, 2: {2: 'image22'}}}
en 'string'
> {'1': {'1': {'1': 'image1', '2': 'image2'}, '2': {'2': 'image22'}}}
qui devenaient alors 2 clés différentes
=> [cache] Fix pb de conversion entre json et dico

scripts/cache.py, scripts/cache_def.py
Objectif : 
- Pouvoir re-traiter en intégralité (découpage et calcul ortho/graph) d'une ou plusieurs OPIs déjà traitées.
Modifications : 
- meilleure gestion du nombre de cpu utilisé : ajout d'une option --processors (par défaut cpu_count()-1)
- ajout d'une option --reprocessing (pris en compte seulement en mode update)
- lors du calcul des ortho et graph :
- regroupement des thread par paquet de 100*cpu_util
- création d'un fichier log pour suivre l'évolution de manière chiffrée de ces regroupement
- ajout d'un block try/except de l'ensemble du processus de traitement
=> [cache] Re-traitement OPI lors d'un update

routes/misc.js, serveur.js
Problème sur l'initialisation du port serveur - si on indique autre valeur que celle par défaut, les requêtes n'aboutissent pas la version de l'API n'est pas récupérée / affichée  
Cette PR propose donc : 
- une correction sur l'initialisation du port de l'API
- une refactorisation du code sur la récupération et affichage de la version de l'API
=> Correction régression port API et refactorisation version

cog_path.js, doc/swagger.yml, gdal_processing.js, itowns/Saisie.js, itowns/index.js, middlewares/branch.js, regress/branch.js, regress/graph.js, regress/patch.js, regress/wmts.js, routes/branch.js, routes/graph.js, routes/patch.js, routes/wmts.js, serveur.js
Pouvoir avoir plusieurs versions des modifications du cache sous forme de branches. C'est la première étape pour la gestion du travail collaboratif sur PackO (c'est-à-dire à plusieurs sur un même cache). Pour éviter les conflits et les incohérences, chaque utilisateur devra travailler seul, sur sa branche. Il faudra ajouter des outils de fusion de branches ainsi que des vérifications permettant de s'assurer que deux personnes ne travaillent pas en même temps sur une branche.
Cela fera l'objet d'au moins 2 autres PR.
Cette première PR permet:
=> Gestion des branches de cache basé sur les caches en COG

routes/wmts.js
En lien avec #181 
Deux corrections:
- on passe tous les noms de paramètres en lettres capitales sur les requêtes WMTS pour être insensible à la casse (conformément à la spec du protocole)
- on ajoute le numéro de la branche dans l'URL des services donnée par le GetCapabilities
La compatibilité a été vérifiée avec QGIS (qui utilise des noms de paramètre en capitale) et avec les commandes gdal (qui utilise du CamelCase). 
Exemple de commande gdal (à tester sur le cache_test):
```
gdalwarp "WMTS:http://localhost:8081/0/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities,layer=ortho" out-packo.tif -te 230600 6759400 230800 6759700 -tr 0.8 0.8
```
=> fix WMTS for gdal

itowns/Saisie.js
La PR précédente, permettant la persistance de la propriété 'visible' d'une couche à entrainé une régression sur la sélection d'une nouvelle OPI restant a non visible.
Cette PR vise à corriger ce bug.
=> fix(monitor): set opi to visible after select

itowns/Saisie.js, itowns/index.js
modifications mineures pour pouvoir utiliser itowns avec la nouvelle version de l'API
Il faut ajouter un paramètre 'namecache' dans l'url pour utiliser un cache en particulier.
si 'namecache' n'est pas renseigné ou n'existe pas, itowns va utiliser le 1er cache disponible dans la base de données.
=> feat(monitor): connexion to DB

itowns/Saisie.js, itowns/index.js
Pouvoir choisir l'épaisseur des contours (demande de l'utilisateur final).
Le shader en place permet déjà de modifier l'épaisseur avec le paramètre **effect_parameter** mais il n'y avait pas de moyen dans l'interface pour modifier ce paramètre. Dans cette PR, on modifie la fonction **addImageryLayerGUI** d'iTowns pour gérer cette option.
Le résultat: le paramètre est accessible pour la couche **Contour** avec un curseur sous le nom **thickness**.
Cette solution n'est pas totalement satisfaisante parce qu'il faudrait veiller à rester compatible avec les évolutions de la méthode **addImageryLayerGUI**: à discuter avec l'équipe du projet iTowns.
=> ajout d'une interface pour choisir l'épaisseur des contours

ressources/LAMB93_20cm.json, ressources/LAMB93_5cm.json
Correctoin du calcul du cache, seulement 8 niveaux étaient calculés avec deux couches de COGs (10 niveaux possibles)
=> fix(cache): use 5 levels for 2nd layer of COGs

scripts/cache_def.py
La mise à jour de la boundingBox du cache est fausse, cela conduit à un mauvais GetCapabilities et à des problèmes de prise en compte de l'emprise du flux dans QGis et lors de l'utilisation de gdal pour des exports raster.
Erreur de copie/coller entre LowerCorner et UpperCorner
=> fix(cache): fix boundingBox update

.github/workflows/coveralls.yml, db/db.js, doc/swagger.yml, middlewares/branch.js, middlewares/cache.js, middlewares/patch.js, middlewares/returnMsg.js, middlewares/wmts.js, package.json, paramValidation/validateParams.js, regress/1_file.js, regress/2_cache.js, regress/3_branch.js, regress/3_graph.js, regress/4_patch.js, regress/4_wmts.js, routes/cache.js, routes/file.js, routes/graph.js, routes/patch.js, routes/wmts.js
Objectifs :
- utiliser le fait que l'attribut num d'un patch est automatiquement attribué par la base de données (ne plus avoir a le renseigné au niveau de l'API)
- Augmenter la couverture des tests de non régression
Modifications :
- Suppression de la variable num lors de l'insert d'un patch
- correction de message de debug dans db.js
- ajout Validation param pour le fichier overviews
- Fix de la route GET file
- Modification de la gestion des erreurs du ValideParam
- Modification du SQL GET caches et GET branches pour que la liste soit ordonnée
- Ajout de test de non régression
- lancer les tests coveralls pour toutes PR et non seulement pour une PR vers master
=> Suppression num patch dans l'API et Augmenter la couverture des test

db/db.js, middlewares/patch.js
Améliorer l'export de la liste des dalles impactées dans les GeoJson.
Pour le moment on export 3 tableaux **x**, **y**, **z** alors qu'il serait préférable d'avoir un tableau **slabs** contenant des triplets [x,y,z]
=> feat(API): add slabs in patches GeoJson export

itowns/Viewer.js, itowns/index.js
première partie du ticket #233 
pour le moment pas de modification côté création du cache ou API, simplement on crée un dataSet.limitsForGraph avec uniquement les niveaux correspondant au COG réellement mis à jour.
=> fix(monitor): do not display graph/contour for 2nd COG level

itowns/Editing.js, itowns/index.js
Pouvoir déselectionner l'OPI pour revenir à un affichage sans la couche OPI.
Utilisation de la touche **Escape**.
Au passage on a aussi corrigé un bug dans le cas où l'utilisateur sélectionne une OPI hors zone et on a supprimé un paramètre non utilisé dans le constructeur de **Editing**.
=> feat(monitor): Escape key to unselect OPI

.github/workflows/coveralls.yml, .github/workflows/lint-javascript.yml, itowns/package-lock.json, itowns/package.json, package-lock.json, package.json
Diminuer le nombre de vulnérabilités lors du npm install
Parmi les modifications importantes : 
* pour le moniteur itowns :    
* passage à itowns 2.35 la dernière version stable, dernière release, à la place de 2.34
* mise à jour des paquets
=> il reste 12 (9 modérées, 7 hautes), au lieu de 16 (9 modérées, 7 hautes) ; ce gain a été sans danger, mais corriger plus, c'est pas sans danger pour le bon fonctionnement ("breaking changes"), donc je pense que c'est déjà pas mal et qu'on verra plus tard
* pour l'API : 
* passage au node 14, la dernière version stable, à la place du 10
* mise à jour des paquets qui en découle
=> il reste 3 vulnérabilités (modérées), au lieu de 14 (9 modérées, 5 hautes)
=> fix(API,monitor): npm vulnerabilities

README.md, gdal_processing.js, itowns/Editing.js, middlewares/patch.js
Depuis le commit 3b673edd459d3b87127150a6786288ff42fa7404 les COG modifiés dans le cache (pour l'ortho et le graph) n'ont ni géoref ni SRS.
Il faut ajouter la copie du geoTransform et du srs.
Attention:
- il faut veiller à bien utiliser les API Async de gdal-async (**geoTransformAsync**, **srsAsync**)
- il peut y avoir des interférences avec une config locale de GDAL: en particulier la variable PROJ_LIB. Dans ce cas, le SRS peut être non reconnu et l'image obtenue s'affiche dans QGis en SRS inconnu. Si nécessaire, faire un "unset PROJ_LIB" avant de lancer l'API
=> fix(API): fix GeoTransform on cache

README.md, db/db.js, doc/swagger.yml, itowns/Branch.js, itowns/Controller.js, itowns/Editing.js, itowns/Viewer.js, itowns/index.html, itowns/index.js, itowns/package-lock.json, itowns/package.json, middlewares/vector.js, routes/vector.js, sql/packo.sql
Objectif:
- Pouvoir ajouter une couche d'alerte pour parcourir les entités une par une et changer leur état.
Modifications:
- mise à jour itowns 2.36.1 permettant la gestion des couches de vecteurs ponctuel
- ajout d'un menu déroulant "alert" permettant de sélectionner une couche de vecteur annexe ajoutée qui deviendra la couche d'alerte
- une fois cette couche sélectionnée, il y a centrage sur la première entité et le style de cette couche est modifié en lien avec la propriété 'status' de chaque entité
- on peut se déplacer d'entités en entités à l'aide des flèche droite et gauche (ainsi que haut, bas) et cliquer sur une entité pour en changer.
- une couche Layer est ajoutée permettant de surligner l'entité sélectionnée
- Des qu'une entité est sélectionnée, 2 nouveaux boutons sont …
=> Gestion de couche d'alerte

README.md, itowns/Controller.js, itowns/index.js, itowns/webpack.config.js
Corrections de bugs en lien avec la PR permettant l'ajout de couche vecteur.
Fix : 
- bug lors de l'ajout d'une couche vecteur et rafraichissement de la couche d'alerte
#258 
- bug lorsque l'on rend la couche d'alerte invisible et entité sélectionnée
#262 (2eme point)
- nouvelle fonctionnalité : pouvoir désélectionner la couche d'alerte
#262 (1er point)
- fix bug lors de la mise à jour du champ 'comment' qui n'était pas répertoriée sur la couche courante
Autre :
- Fix d'un bug en lien avec l'upgrade des package webpack
=> Fix : Ajout couche d'alertes

itowns/Editing.js, itowns/Viewer.js, itowns/index.js
Se base sur la PR #260 
Objectifs :
- visualiser les couches vecteurs (sauf patchs) à tout les niveaux
#233 (4eme point)
- ne pas permettre la saisie de polygone à petite échelle
#233 (3eme point)
=> Gestion des couches en fonction du niveau de zoom

itowns/Viewer.js
Fix d'un bug apparaissant lors de la suppression d'un couche vecteur.
Ce bug apparait lorsque l'on essaye de supprimer la *toute* première couche vecteur ajoutée. (première couche ajoutée après avoir poussé le premier cache dans une base de données nouvellement créée).
=> fix(monitor): vectorId and deleteLayer

itowns/index.js
Remplacement du raccourci pour "redo" : "CTRL+Q" au lieu de "CTRL+Y", car "CTRL+Y" crée des conflits d'utilisation dans le navigateur avec pour effet le déplacement de la vue au dezoom par défaut 1/16
=> fix(monitor): shortcut for redo

db/db.js, doc/swagger.yml, middlewares/vector.js, regress/4_vector.js, routes/vector.js
Objectif : 
Limiter l'ajout (et suppression) de ponctuel sur les couches 'Remarques'
Modification : 
- Ajout d'une contrainte sur l'identifiant du vecteur en entrée
- Modification du message de retour
- Mise a jour du swagger et des tests (pour vector.js)
=> Remarks: Modif route ajout/suppression de ponctuel

itowns/Controller.js, itowns/index.js
Correction d'un bug lors du changement de couche d'alerte d'une couche non vide a une couche vide.
Issue #299
=> fix(monitor): hide controllers when changing alert layer to an empty layer

middlewares/branch.js
Changement fs.copyFileSync(src, dest) to fs.writeFileSync(dest, fs.readFileSync(src))
Pour éviter le bug de droit d'écriture qui apparait lors du merge de branches
=> Fix : rebase branche et droit d'ecriture

itowns/Branch.js, itowns/Viewer.js, itowns/index.js
Gestion des erreurs dans le monitor
Ajout d'un nouvel 'event' 'error' qui pourras être émis lorsque le code retourne une erreur et ainsi faire un retour utilisateur.
(Actuellement émis lors d'un nouveau nom de branche vide ou lors d'un drag and drop contenant des fichiers non supportés ou lors d'un drag and drop d'un fichier déjà ajouté)
=> monitor : gestion des erreurs et retour utilisateur

itowns/Branch.js, itowns/Controller.js, itowns/index.js
Ajout d'un nouvel 'event' appelé lors d'un changement de branche. 
L'event création de branche ne fait ainsi plus que la création de branche.
Cela permet de faire du nettoyage sur le controller : 
- refreshDropBox : ajout d'un attribut pour conserver ou non la valeur initiale
=> Nouvel event pour le changement de branche et nettoyage Controller

itowns/Branch.js, itowns/Controller.js, itowns/Editing.js, itowns/Viewer.js, itowns/index.js, sql/packo.sql
PR permettant l'affichage des données liée au Opi
Cette PR ajoute aussi quelques correctifs:
- Permettre l'ajout de plusieurs vecteurs annexe en une seule fois
- Fixer l'ordre des couches sur le Menu
- corriger le message d'erreur lorsque l'on ajoute une remarque sur une couche vierge
Autre modifications:
- suppressions des l'appels a hide() pour les controllers
- refactoring des modifications des source.url au niveau de view.
=> Ajout de la date et heure d'acquisition de l'Opi sélectionnée

itowns/index.js
Correction de la régression permettant au bouton 'clear' d'apparaitre même en mode production.
=> fix(monitor): hide btn clear by default

doc/swagger.yml
Dans swagger.yml, ajout LAMB93_20cm dans TILEMATRIXSET de la route GET /{idBranch}/wmts
=> Ajout LAMB93_20cm pour TILEMATRIXSET

scripts/cache.py, scripts/cache_def.py
Corrections sur la création de cache :
- fichier json de chantier (ticket interne #2108)
- gestion des OPI non présentes dans le graphe (ticket interne #2106)
- prise en compte de 'x' dans nom de cache ir (#344)
- nettoyage suite au rebase précédent
=> fix(cache): gpao file and missing OPI and fix ir cache

scripts/cache.py
Pouvoir paramétrer le calcul du cache pour limiter les échecs de calculs longs dans le service de calcul IGN. (issue #359 )
=> Taille de traitement de generate_tile

itowns/package-lock.json, package-lock.json, package.json
Correction de toutes les vulnérabilités npm sur l'API (5 vulnérabilités majeures) et le client itowns (4 vulnérabilités majeures), toutes liées à minimatch ReDoS (pour plus d'info : https://github.com/advisories/GHSA-f8q6-p94x-37v3)
=> Fix npm vulnerabilities

README.md
Suite à la demande interne d'évolution 2056, j'ai mis à jour la doc et ajouté les commandes curl pour :
- mise en base d'un cache
- export couche(s) vecteur (Remarques ou autre)
- export des retouches
=> docs: add curl commands

gdal_processing.js, itowns/package-lock.json, itowns/package.json, middlewares/patch.js, middlewares/wmts.js, package-lock.json, package.json
Cette PR fait suite et remplace la PR #349
Remplacer jimp avec gdal semble bien améliorer les performances de l'API, notamment dans le cas d'une charge importante - plusieurs clients au même moment
=> Replace jimp by gdal

package-lock.json
Correction API de deux vulnérabilités moyennes *Regular Expression Denial of Service (ReDoS)* liées à la version du paquet cookiejar
=> fix(API): fix ReDoS vulnerability on cookiejar npm package

scripts/cache_def.py
Ticket interne #2109
On utilise maintenant le nom de la colonne géométrie dans le graphe en entrée au lieu d'une valeur par défaut comme actuellement ('geom').
=> fix(cache): use geometry column name instead of default value

itowns/package-lock.json, package-lock.json, package.json
Correction des vulnérabilités node :
- pour l'API : mise à jour de pm2, instanbul-lib-report, braces -> il reste 6 vulnérabilités pour lesquelles il faut attendre la correction
- pour itowns : mise à jour de semver et ws , ce qui corrige toutes les vulnérabilités
=> Fix vulnerabilities

README.md, scripts/process_qlayers.py
La classe QGIS API utilisée pour désactiver le formulaire pop-up a changé de manière cassante dans la nouvelle ltr de l'api qgis 3.34.
J'ai fait le nécessaire pour le script de création de vue qgis et fixé la version minimale de QGIS à 3.34 dans la doc
=> Fix qview - latest qgis api ltr

gdal_processing.js
Constaté sous Windows (pas testé sous Linux), lorsqu'on enchaine rapidement un "undo" avec l'application d'un patch on a fréquemment une erreur de type "EBUSY: resource busy or locked" liée à une commande rename (voir ci-dessous).
Cette erreur est liée au rafraichissement (des commandes WMTS GetTile) qui ouvrent des images avec des gdal.openAsync sans les fermer explicitement. Lorsqu'on demande le "undo", l'API demande à renommer un fichier qui est encore ouvert et cela provoque une erreur.
Cette PR ajoute des "ds.close" pour tous les gdal.openAsync sur des fichiers.
Le plus grave, c'est que cela stoppe le traitement du "undo" en cours de route et on obtient une branche corrompue dans le cache avec un patch partiellement annulé.
node:fs:980
handleErrorFromBinding(ctx);
^
Error: EBUSY: …
=> Fix resource busy erro

README.md, ressources/example_macros_qgis.py, scripts/cache.py, scripts/cache_def.py, scripts/create_qgis_view.py
Évolution des scripts de création du cache : 
- activation des exceptions gdal/ogr, nécessaires surtout dans le cas de l'utilisation des calculs  via la gpao
Évolutions du script de création de la vue QGIS :
-  changement en option obligatoire de l'option nom de la branche  (jusque-là, option facultative,  avec une valeur par défaut 'newBranch') 
-  prise en compte de nombre de canaux de l'ortho et du graphe dans la création des xml correspondants (au lieu de laisser la valeur par défaut "4")
Évolutions macros et de la vue de la vue QGIS  :  
- ajout de nouveaux paramètres à la macro : STYLE, PIXELSIZEX, PIXELSIZEY, CRS - jusque-là, ils avaient des valeurs en dur (style="RVB", pixel=0.05, crs="2154"), ce qui ne permettait pas de travailler, au moins pas facilement, avec des caches …
=> Enhance qgis view & macros
